### PR TITLE
documentation fix for #8

### PR DESCRIPTION
**Pull request by TashaSkyUp**
fixes documentation around #8

### CODE REVIEW

**Comment by venatiodecorus** [comment]
> You can just do `git lfs clone https://huggingface.co/PixArt-alpha/PixArt-XL-2-1024-MS`

you also have to do `git lfs install`. i haven't used git lfs much at all so i wasn't aware of this.

**Comment by DmytroSokhach** [comment]
For me it was enough to navigate `ComfyUI\models\text_encoders` and run
`git clone https://huggingface.co/PixArt-alpha/PixArt-XL-2-1024-MS`
40GB by the way 🙃

**Comment by kvochko** [comment]
@TashaSkyUp thank you! We want the README to help users on windows as well, so I added a link to git-lfs installation instructions in https://github.com/Lightricks/ComfyUI-LTXVideo/pull/14. Please comment there if you have any suggestions!

**Comment by vu0tran** [comment]
Screenshot 2024-11-23 at 12 06 34 PM

I'm missing the LTXV CLIP Model Loader even though I've installed the LTXV Custom node through manager. Any idea what's happening?

**Comment by DmytroSokhach** [comment]
> I'm missing the LTXV CLIP Model Loader even though I've installed the LTXV Custom node through manager. Any idea what's happening?

@vu0tran Not sure why it is not available for you. I would try re-installing the ComfyUI-LTXVideo node:
1. Close ComfyUI
1. Delete ComfyUI\custom_nodes\ComfyUI-LTXVideo
3. Restart ComfyUI
4. Install ComfyUI-LTXVideo from Package Manager **>>at this point check for Console logs for errors<<**
1. Restart ComfyUI
1. Let it install required dependencies **>>at this point check for Console logs for errors<<**

**Comment by vu0tran** [comment]
I got it resolved. For those having similar issues, it was due to me not upgrading my ComfyUI. There's a missing enum to the text_encoders folder. Thank you!

**Pull request closed without merging**
